### ISSUE TITLE
Error when installing Trajectories.

### ISSUE THREAD

**Issue by juanpide** [EHDEN/Trajectories#24]
Hello.

When I try to install Trajectories (following the https://github.com/oxford-pharmacoepi/Studyathon_LCPASC/CodeToRun.R code) I get this error:

`remotes::install_github("EHDEN/Trajectories")
`
```
Downloading GitHub repo EHDEN/Trajectories@HEAD
Error: Failed to install 'Trajectories' from GitHub:
  Missing commas separating Remotes: 'OHDSI/CohortGenerator
    OHDSI/CirceR'
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
```

I'm using R 4.1.2 (I can't upgrade it because I don't have permissions in my university).
Windows 10.

**Comment by smusali** [comment]
Hey @skanskan,

Thanks for reporting this issue!

In #25, we revert back the recent changes to ensure the package is stable.

**Comment by juanpide** [comment]
Excuse my ignorance, @smusali.
But then how can I install the right version?

**Comment by SulevR** [comment]
It is now in master branch. So, regular git clone (or download zip from master branch) should do the work.

**Comment by smusali** [comment]
> Excuse my ignorance, @smusali. But then how can I install the right version?

Hey @skanskan,

We reverted it back to its stable form; so, you can use the package in the same way as you used it before this issue happened.

**Comment by juanpide** [comment]
OK, now it works, 
Thank you.
